apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quorum.fullname" . }}
  labels:
    {{- include "quorum.labels" . | nindent 4 }}
  annotations:
    # Required: allows this SA to act as an OpenShift OAuth client.
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "quorum.fullname" . }}"}}
